-- Gabarits de courriels éditables (sujet + zones de texte, fr/en)
-- + langue préférée de l'utilisateur pour les courriels transactionnels.
CREATE TABLE `email_templates` (
	`template_key` varchar(50) NOT NULL,
	`locale` varchar(2) NOT NULL DEFAULT 'fr',
	`subject` varchar(255) NOT NULL,
	`zones` json NOT NULL,
	`updated_at` datetime NOT NULL,
	`updated_by` int,
	CONSTRAINT `email_templates_pk` PRIMARY KEY(`template_key`,`locale`)
);--> statement-breakpoint
ALTER TABLE `users` ADD `preferred_locale` varchar(2) NOT NULL DEFAULT 'fr';--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('confirmation', 'fr', 'Confirmation de votre réservation LUDOV', '{"intro":"Bonjour {userName},\\nVotre réservation chez LUDOV a bien été confirmée. Nous avons hâte de vous accueillir !","important":"Arrivez 5 minutes à l''avance afin de valider votre présence.\\nApportez une pièce d''identité valide.\\nSi vous souhaitez modifier votre réservation, contactez-nous au moins 24h à l''avance.","outro":"Si vous avez des questions, notre équipe est là pour vous aider."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('confirmation', 'en', 'Your LUDOV reservation is confirmed', '{"intro":"Hello {userName},\\nYour LUDOV reservation has been confirmed. We look forward to welcoming you!","important":"Arrive 5 minutes early to check in.\\nBring a valid ID.\\nIf you need to change your reservation, contact us at least 24 hours in advance.","outro":"If you have any questions, our team is here to help."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('reminder', 'fr', 'Rappel de votre réservation LUDOV', '{"intro":"Bonjour {userName},\\nPetit rappel : votre réservation chez LUDOV approche !","outro":"Si vous ne pouvez pas vous présenter, merci d''annuler votre réservation depuis la plateforme."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('reminder', 'en', 'Reminder: your upcoming LUDOV reservation', '{"intro":"Hello {userName},\\nJust a reminder: your LUDOV reservation is coming up!","outro":"If you cannot make it, please cancel your reservation on the platform."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('reset_password', 'fr', 'Réinitialisation de votre mot de passe LUDOV', '{"intro":"Bonjour,\\nNous avons reçu une demande de réinitialisation de votre mot de passe pour votre compte LUDOV.\\nVotre mot de passe a été réinitialisé avec succès.\\nLors de votre prochaine connexion, veuillez cliquer sur « Première connexion » afin de définir un nouveau mot de passe.\\nSi vous n''êtes pas à l''origine de cette demande, veuillez contacter notre support immédiatement.","outro":"Si vous avez des questions ou éprouvez des difficultés, n''hésitez pas à nous contacter."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('reset_password', 'en', 'Your LUDOV password has been reset', '{"intro":"Hello,\\nWe received a request to reset the password of your LUDOV account.\\nYour password has been reset successfully.\\nOn your next login, please click “First login” to set a new password.\\nIf you did not request this, please contact our support immediately.","outro":"If you have any questions or difficulties, feel free to contact us."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('welcome', 'fr', 'Bienvenue chez LUDOV !', '{"intro":"Bonjour,\\nNous sommes ravis de vous accueillir au sein des laboratoires de LUDOV !\\nVous pouvez dès maintenant explorer la plateforme, consulter le catalogue et effectuer vos réservations.","outro":"Si vous avez des questions concernant vos emprunts, vos réservations ou le fonctionnement de la plateforme, n''hésitez pas à nous contacter."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('welcome', 'en', 'Welcome to LUDOV!', '{"intro":"Hello,\\nWe are delighted to welcome you to the LUDOV laboratories!\\nYou can now explore the platform, browse the catalog and make reservations.","outro":"If you have any questions about your loans, reservations or how the platform works, feel free to contact us."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('otp', 'fr', 'Code OTP - LUDOV réservation', '{"body":"Votre code de vérification LUDOV est : {otpCode}\\nCe code expire dans 15 minutes.\\nSi vous n''êtes pas à l''origine de cette demande, ignorez ce courriel."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('otp', 'en', 'OTP code - LUDOV reservation', '{"body":"Your LUDOV verification code is: {otpCode}\\nThis code expires in 15 minutes.\\nIf you did not request this, please ignore this email."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('cancellation', 'fr', 'Annulation de votre réservation LUDOV', '{"intro":"Bonjour {userName},\\nVotre réservation chez LUDOV a été annulée par notre équipe. Vous trouverez les détails ci-dessous.","outro":"Vous pouvez effectuer une nouvelle réservation en tout temps depuis la plateforme LUDOV.\\nSi vous avez des questions concernant cette annulation, notre équipe est là pour vous aider."}', NOW());--> statement-breakpoint
INSERT INTO `email_templates` (`template_key`, `locale`, `subject`, `zones`, `updated_at`) VALUES ('cancellation', 'en', 'Your LUDOV reservation has been cancelled', '{"intro":"Hello {userName},\\nYour LUDOV reservation has been cancelled by our team. You will find the details below.","outro":"You can make a new reservation at any time on the LUDOV platform.\\nIf you have any questions about this cancellation, our team is here to help."}', NOW());
