-- Guide Markdown réécrit : exemples « ce que vous écrivez / ce que ça donne »,
-- section « erreurs fréquentes » et rappel du flux d'édition. Le contenu vit en
-- base (table `docs`), d'où cette migration plutôt qu'un fichier.
INSERT INTO `docs` (`slug`, `locale`, `title`, `content`, `is_public`, `updated_at`)
VALUES ('markdown-guide', 'fr', 'Guide Markdown', '# Guide Markdown\n\nLe Markdown met en forme du texte avec quelques caractères simples. Vous écrivez dans le champ « Contenu (Markdown) » et le rendu apparaît aussitôt dans l''aperçu, à droite.\n\n## L''essentiel\n\n| Vous écrivez | Ce que ça donne |\n| --- | --- |\n| `**important**` | **important** |\n| `*nuance*` | *nuance* |\n| `[LUDOV](https://ludov.ca)` | [LUDOV](https://ludov.ca) |\n\n## Titres\n\nLes titres découpent la page et alimentent le menu de navigation, à gauche. Un seul titre de niveau 1 par page, tout en haut.\n\n```\n# Titre de la page\n## Grande section\n### Sous-section\n```\n\nRègle simple : un dièse de plus, un niveau plus bas. L''espace après le dièse est obligatoire.\n\n## Paragraphes\n\nLaissez une ligne vide entre deux paragraphes. Sans ligne vide, les deux phrases se retrouvent collées dans le même paragraphe.\n\n```\nPremier paragraphe.\n\nDeuxième paragraphe.\n```\n\n## Listes\n\n```\n- Première puce\n- Deuxième puce\n\n1. Première étape\n2. Deuxième étape\n```\n\nPour imbriquer une liste, décalez de deux espaces :\n\n```\n- Plateforme\n  - Manette\n  - Câble d''alimentation\n```\n\n## Liens\n\n```\n[Texte affiché](https://exemple.com)\n```\n\n## Images\n\nCliquez sur « Insérer une image », au-dessus du champ d''édition : l''image est téléversée et la ligne Markdown est ajoutée a la fin du texte. Vous pouvez ensuite la déplacer où vous voulez.\n\n```\n![Description de l''image](/api/admin/images/dossier/fichier.png)\n```\n\nLe texte entre crochets décrit l''image pour les personnes qui utilisent un lecteur d''écran.\n\n## Tableaux\n\n```\n| Colonne | Description |\n| --- | --- |\n| Valeur | Explication |\n```\n\nLa deuxième ligne, faite de tirets, est obligatoire : c''est elle qui sépare l''en-tête du contenu.\n\n## Citations\n\n```\n> À retenir : annuler une réservation libère la plateforme.\n```\n\n> À retenir : annuler une réservation libère la plateforme.\n\n## Blocs de code\n\nEncadrez le texte par une ligne de trois accents graves avant et après pour l''afficher tel quel, sans mise en forme. C''est ce qui est utilisé dans tous les exemples de cette page.\n\n## Séparateur\n\nTrois tirets seuls sur une ligne tracent un trait horizontal :\n\n```\n---\n```\n\n## Erreurs fréquentes\n\n| Ce que vous voyez | Cause | Correction |\n| --- | --- | --- |\n| Deux phrases collées | pas de ligne vide entre elles | ajouter une ligne vide |\n| Le titre s''affiche en texte normal | espace manquant après le dièse | écrire `## Titre` |\n| Le tableau reste en texte brut | ligne de tirets absente | ajouter la ligne de separation sous l''en-tête |\n| La liste reste en texte brut | espace manquant après le tiret | écrire `- Élément` |\n\n## Avant d''enregistrer\n\n- Relisez l''aperçu, à droite : c''est exactement ce que verront les autres.\n- Vérifiez que les titres se suivent dans l''ordre (1, puis 2, puis 3).\n- Cliquez sur « Enregistrer », en haut à droite.\n', 0, NOW())
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `updated_at` = NOW();
