name: PR CI
on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run Vitest tests with coverage
        run: npx vitest run

      - name: Build check
        env:
          NEXT_TELEMETRY_DISABLED: 1
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: npm run build
